Texture: 'ewogICJ0aW1lc3RhbXAiIDogMTcxMjQyMjU5MjkzMCwKICAicHJvZmlsZUlkIiA6ICJkN2YxZDZlYmNhMzk0ZjBkOGNhNTFiODg4OWU4MTZiNSIsCiAgInByb2ZpbGVOYW1lIiA6ICJEb3V0b3JCaXNjb2l0byIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kYzBmY2Y1OWE1N2U1NjI3MmE3OWNkZjBjYjExOTY1YjFiZWQ2NWVjNTA2ZTA1ODdlN2ZmZTk0OTY2MGZlOTQ0IgogICAgfQogIH0KfQ=='
Signature: 'JxXXXXrWHalaMhmDtXKEOi9lDTYBskvwRYAiH1QNy6hsoHFgRTAzmS8JqvwXS0CmocJa7+t8cvomdkQmpgfmPYFMJ+RyFjN69T9ZgnnDOYffuAtoX824pcnEqKL6X5Zp4OyE216GW7ez/tPZalbG4oZKuzY4H6mlV3dhLFT6E1iuzac+4Iae+eXhlERnRK0gOcMyccOmAsNjpzRNfnMLHqrhcbEsYf3dmZv5+j8BjUzqC8GjxSzwYEftYKlzA3lf3JfUWNYeK19K5uqz3fVDbnZ7Ap06ufutrEKtLI5CvnKkO3upWL1F3afpjJ5hL/X9M8rtfOmb1ZfSRu2xkaOCkr07SsojFYcCveUmkRcL9NXDSRdyqxvduZdbf8VME8EjRZIQp9c0vdWvkZZ6FwGYE8z2ucVi47Jxui2KkXqFGvHDGQw3GPTWocIbO0mp5ux4XY5DDpzYmdeza2ZA3DNN/iEhm5SiLel4V90tGbc3NHYX8T0A79RzRgnLYCL+FmfvYdpHTysM2p9xUXhCSlKbIDjFGlV/eqO89ThmQPC6MNRwagOGCW6eRRZWh+kPxJ7jNPzE/zXNIbixUEj5FJ3h36b3WduzcTxfscMhDpG5kEMNyRI1hnMI93g1HzkM2WkwujQo6GzLkFnYm7js6LXfojum6pvan1M6GI8ZojAcQOw='

spawn:
  world: world
  x: -10.608
  y: 62.0
  z: 27.151
  yaw: -179.8
  pitch: -0.4

database:
  host: "200.97.149.48"
  port: 3306
  database: "s4_Core"
  username: "u4_SwTPFJ1Jj7"
  password: "k^gYYmLWrX@Jcj9B!=k5AEc1"
  pool-size: 10
